# Generated by Django 5.0 on 2023-12-25 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=20)),
                ('post_description', models.CharField(max_length=200)),
                ('post_content', models.CharField(max_length=300)),
                ('post_creationdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_ispublic', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
